cmake_minimum_required(VERSION 3.0)

function(test_function)
    foreach(arg ${ARGN})
        message( STATUS "args-->" ${arg} )
    endforeach()
endfunction()

macro(source_group_by_dir all_files strip_path)
    message("${strip_path}")
    if(MSVC)    
        foreach(single_file ${${all_files}})
            message("${single_file}")
            string(REGEX REPLACE "(${strip_path})/(.*)$" \\2 relative_fpath ${single_file})
            string(REGEX MATCH "^(.*)/(.*)\\.[^.]*$" dummy ${relative_fpath})
            set(file_path ${CMAKE_MATCH_1})
            message("${file_path}")
            string(REPLACE "/" "\\" file_group_name ${file_path})
            message("group name: ${file_group_name}")
            source_group(${file_group_name} FILES ${single_file})
        endforeach(single_file)
    endif(MSVC)
endmacro(source_group_by_dir)

SET(platform win)
