/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_caizb_jnicalljava_jnicall */

#ifndef _Included_com_example_caizb_jnicalljava_jnicall
#define _Included_com_example_caizb_jnicalljava_jnicall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_caizb_jnicalljava_jnicall
 * Method:    startcalljava
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_caizb_jnicalljava_jnicall_startcalljava
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
